services:
  - type: web
    name: todo-app
    runtime: python
    buildCommand: ./build.sh
    startCommand: python -m gunicorn todo.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: todo.settings
