services:
  - type: web
    name: todo-app
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input
    startCommand: python manage.py migrate && python -m gunicorn todo.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health/
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: DJANGO_SETTINGS_MODULE
        value: todo.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: ALLOWED_HOSTS
        value: todo-emug.onrender.com
      - key: DATABASE_URL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false

databases:
  - name: todo-db
    databaseName: todo_db
    user: todo_user
    plan: free
