# Generated by Django 5.0.6 on 2026-03-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_created_at_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='username',
            field=models.CharField(default='temp_user', max_length=150),
        ),
    ]
